/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(bchdecoder_bb.h) */
/* BINDTOOL_HEADER_FILE_HASH(d0fae34ea02b92f01e9807494c4aa0e6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/bchcoder/bchdecoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bchdecoder_bb_pydoc.h>

void bind_bchdecoder_bb(py::module &m) {

  using bchdecoder_bb = ::gr::bchcoder::bchdecoder_bb;

  py::class_<bchdecoder_bb, gr::block, gr::basic_block,
             std::shared_ptr<bchdecoder_bb>>(m, "bchdecoder_bb",
                                             D(bchdecoder_bb))

      .def(py::init(&bchdecoder_bb::make), py::arg("bchtype"),
           D(bchdecoder_bb, make))

      ;
}
